# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7137ed03d3191774c656e2678dbc225dd3b6857051f59cd56891a6ca94a24981761bad39d44abf271572822029e1c516277d5cbaef17f431eb99c7f63bc1a061

test:
  secret_key_base: e39ec58090c8f9b2a98c657042c709e0a9032469df30d7e7fba6f604a3ed07a3be081120ad8c95e32357d1fb1f564fa4972c18fc2586c57b3513176a58fea990

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
